allowBuilds:
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@mui/core-downloads-tracker@9.4.0'
  - '@mui/icons-material@9.4.0'
  - '@mui/material@9.4.0'
  - '@mui/private-theming@9.4.0'
  - '@mui/styled-engine@9.4.0'
  - '@mui/system@9.4.0'
  - '@mui/types@9.4.0'
  - '@mui/utils@9.4.0'
  - '@rspack/binding-darwin-arm64@2.2.1 || 2.2.3'
  - '@rspack/binding-darwin-x64@2.2.1 || 2.2.3'
  - '@rspack/binding-linux-arm64-gnu@2.2.1 || 2.2.3'
  - '@rspack/binding-linux-arm64-musl@2.2.1 || 2.2.3'
  - '@rspack/binding-linux-ppc64-gnu@2.2.1 || 2.2.3'
  - '@rspack/binding-linux-riscv64-gnu@2.2.1 || 2.2.3'
  - '@rspack/binding-linux-riscv64-musl@2.2.1 || 2.2.3'
  - '@rspack/binding-linux-s390x-gnu@2.2.1 || 2.2.3'
  - '@rspack/binding-linux-x64-gnu@2.2.1 || 2.2.3'
  - '@rspack/binding-linux-x64-musl@2.2.1 || 2.2.3'
  - '@rspack/binding-wasm32-wasi@2.2.1 || 2.2.3'
  - '@rspack/binding-win32-arm64-msvc@2.2.1 || 2.2.3'
  - '@rspack/binding-win32-ia32-msvc@2.2.1 || 2.2.3'
  - '@rspack/binding-win32-x64-msvc@2.2.1 || 2.2.3'
  - '@rspack/binding@2.2.1 || 2.2.3'
  - '@rspack/cli@2.2.1 || 2.2.3'
  - '@rspack/core@2.2.1 || 2.2.3'
  - jotai@3.0.0
  - '@vtecx/vtecxdocument@1.0.4'
  - '@vtecx/vtecxnext@3.3.1'
