import './globals.css'
import type { Metadata } from 'next'
import { Providers } from '@/components/providers'
import { RouterMounting } from '@/components/routermounting'


export async function generateMetadata(): Promise<Metadata> {
  const vtecxUrl = process.env.VTECX_URL ?? ''
  const match = vtecxUrl.match(/^https?:\/\/([^.]+)\.vte\.cx/)
  const serviceName = match?.[1]
  return {
    title: serviceName ? `${serviceName} | vtecxnextblank` : 'vtecxnextblank',
    description: 'Generated by ReflexWorks'
  }
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <RouterMounting>{children}</RouterMounting>
        </Providers>
      </body>
    </html>
  )
}
